### ISSUE TITLE
iOS11 No Worky

### ISSUE THREAD

**Issue by pangia** [deni2s/IBCustomFonts#10]
I know this probably is not maintained any longer.. but iOS11 broke it.  Any chance of taking a look?  It is still a great utility. Thanks!

**Comment by deni2s** [comment]
Will try to look at it!

**Comment by pangia** [comment]
Great. Thanks!  It looks as if iOS11 made some changes to 'fontWithDescriptor', I played around with it a bit without luck.

**Comment by deni2s** [comment]
Added iOS 11 support in 1.1 release
