### ISSUE TITLE
 font  become big

### ISSUE THREAD

**Issue by zjz2020** [deni2s/IBCustomFonts#11]
What is the reason for using this method  the font  become big

**Comment by deni2s** [comment]
Probably your custom font has bigger font size compared to the one you are replacing? 
Need more details if there is an issue.

**Comment by zjz2020** [comment]
first.  I drag  AGBuchBQ-Regular.otf  in projects
second . I pod your code 
third.  I add  IBCustomeFonts  --> Helvetica  : AGBuchBQ-Regular  in infoPlist

the  font  in my projects  become too big

thank you

**Comment by zjz2020** [comment]
![Uploading Simulator Screen Shot 2017年11月6日 下午8.25.41.png…]()
![Uploading Simulator Screen Shot 2017年11月6日 下午8.26.48.png…]()

**Comment by deni2s** [comment]
I don't see the screenshots.

Pod might be outdated, please include UIFont+IBCustomFonts.m in your project manually.

**Comment by deni2s** [comment]
Please try with attached project.
[IBCustomFonts.zip](https://github.com/deni2s/IBCustomFonts/files/1447560/IBCustomFonts.zip)

**Comment by zjz2020** [comment]
Thank you

**Comment by deni2s** [comment]
Does it work? Can I close this issue?

**Comment by deni2s** [comment]
Closing the issue after no response for 7 days.
